import js from "@eslint/js";

const browserGlobals = {
  window: "readonly",
  document: "readonly",
  console: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  setInterval: "readonly",
  clearInterval: "readonly",
  requestAnimationFrame: "readonly",
  cancelAnimationFrame: "readonly",
  CustomEvent: "readonly",
  Event: "readonly",
  HTMLElement: "readonly",
  Element: "readonly",
  Node: "readonly",
  navigator: "readonly",
  localStorage: "readonly",
  sessionStorage: "readonly",
  indexedDB: "readonly",
  fetch: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly",
  Blob: "readonly",
  File: "readonly",
  FileReader: "readonly",
  FormData: "readonly",
  Headers: "readonly",
  Request: "readonly",
  Response: "readonly",
  AbortController: "readonly",
  AbortSignal: "readonly",
  MutationObserver: "readonly",
  ResizeObserver: "readonly",
  IntersectionObserver: "readonly",
  performance: "readonly",
  history: "readonly",
  location: "readonly",
  screen: "readonly",
  CSS: "readonly",
  crypto: "readonly",
  TextEncoder: "readonly",
  TextDecoder: "readonly",
  confirm: "readonly",
  prompt: "readonly",
  alert: "readonly",
  getComputedStyle: "readonly",
  matchMedia: "readonly",
  queueMicrotask: "readonly",
  structuredClone: "readonly",
  atob: "readonly",
  btoa: "readonly",
  EventTarget: "readonly",
  MouseEvent: "readonly",
  KeyboardEvent: "readonly",
  PointerEvent: "readonly",
  DragEvent: "readonly",
  FocusEvent: "readonly",
  InputEvent: "readonly",
  WheelEvent: "readonly",
  MessageEvent: "readonly",
  ErrorEvent: "readonly",
  CloseEvent: "readonly",
  AudioContext: "readonly",
  WebSocket: "readonly",
  XMLHttpRequest: "readonly",
  Image: "readonly",
  Worker: "readonly",
  ServiceWorker: "readonly",
  ServiceWorkerRegistration: "readonly",
  IDBKeyRange: "readonly",
  CSSStyleSheet: "readonly",
  CSSStyleDeclaration: "readonly",
  CanvasRenderingContext2D: "readonly",
  WebGLRenderingContext: "readonly",
  SVGElement: "readonly",
  Symbol: "readonly",
  Map: "readonly",
  Set: "readonly",
  WeakMap: "readonly",
  WeakSet: "readonly",
  Promise: "readonly",
  Proxy: "readonly",
  Reflect: "readonly",
  globalThis: "readonly",
  self: "readonly",
};

export default [
  {
    ignores: ["node_modules/**", "build/**", "dist/**", "vendor/**"],
  },
  js.configs.recommended,
  // Default: browser JS files
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: browserGlobals,
    },
  },
  // Service worker files
  {
    files: ["sw.js", "**/sw.js", "**/*.sw.js"],
    languageOptions: {
      globals: {
        ...browserGlobals,
        self: "readonly",
        caches: "readonly",
        importScripts: "readonly",
        clients: "readonly",
        skipWaiting: "readonly",
        ExtendableEvent: "readonly",
        FetchEvent: "readonly",
        InstallEvent: "readonly",
        ActivateEvent: "readonly",
        CacheStorage: "readonly",
        Cache: "readonly",
        Ultraviolet: "readonly",
        UVServiceWorker: "readonly",
      },
    },
  },
  // Node.js build/tool scripts
  {
    files: ["tools/**/*.js", "*.config.js"],
    languageOptions: {
      globals: {
        process: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        Buffer: "readonly",
        require: "readonly",
        module: "readonly",
        exports: "readonly",
        global: "readonly",
      },
    },
  },
  // Jest test files
  {
    files: ["tests/**/*.js", "**/*.test.js", "**/*.spec.js"],
    languageOptions: {
      globals: {
        describe: "readonly",
        test: "readonly",
        it: "readonly",
        expect: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        jest: "readonly",
        global: "readonly",
      },
    },
  },
];
